# Generated by Django 5.2.9 on 2025-12-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0002_alter_myusers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
