# Generated by Django 5.2.9 on 2025-12-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0003_alter_myusers_comments_alter_myusers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='comments',
        ),
        migrations.AddField(
            model_name='myusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
